version: "3.8"
services:
  HUB:
    image: selenium/hub
    container_name: myHub
    ports:
      - "4444:4444"
    networks:
      - my_network
  
  CHROME:
    image: selenium/node-chrome
    depends_on:
      - HUB
    environment: 
      - HUB_HOST=HUB
      - HUB_PORT=4444
    volumes: 
      - /dev/shm:/dev/shm
    networks:
      - my_network
    deploy:
      replicas: 2

  FIREFOX:
    image: selenium/node-firefox
    depends_on:
      - HUB
    environment: 
      - HUB_HOST=HUB
      - HUB_PORT=4444
    volumes: 
      - /dev/shm:/dev/shm
    networks:
      - my_network
    deploy:
      replicas: 2

networks:
  my_network:
    name: grid